### Create a new user

POST http://localhost:3001/auth/signup
content-type: application/json

{
  "email": "qwe@qwe.com",
  "password": "qwe123qwe"
}

### Find a particular user with a given ID
GET http://localhost:3001/auth/2

### Find all users with a diven email
GET http://localhost:3001/auth?email=qwe@qwe.com

### Delete a user given id
DELETE http://localhost:3001/auth/132123

### Update a user
PATCH  http://localhost:3001/auth/2
content-type: application/json

{
  "password": "qwe123qwe123"
}